### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#10]
Documentation needs to be filled (not code comment docs):

- [x] Index/main page
  - [x] Introduction (#45)
  - [x] Installation
- [x] Custom loaders (#49)
- [x] Model manipulation (#69)

**Comment by pllim** [comment]
We can probably copy and paste some general stuff from http://www.stsci.edu/institute/software_hardware/specview

**Comment by pllim** [comment]
I am going to attempt to add something to "model manipulation" next. After that, we can close this. FYI.
