### ISSUE TITLE
Command line usage should use argparse?

### ISSUE THREAD

**Issue by eteq** [nmearl/pyfocal#101]
I was surprised to find that ``pyfocal --help`` crashes because it thinks ``--help`` is a file I'm asking for.  I suggest using [argparse](https://docs.python.org/3/library/argparse.html) in `App.__init__` or even `main` to do the command-line parsing.  That way a user will see a more traditional and familiar command-line interface, and will make it easier to start adding command-line switches down the road.

**Comment by pllim** [comment]
@eteq , there are plans to do this in #16 but no one has done it yet because it is currently low priority. FYI.

**Comment by eteq** [comment]
Oh, my bad - I missed #16.  Closing this now.
