### ISSUE TITLE
"Trash can" to delete layer doesn't work

### ISSUE THREAD

**Issue by eteq** [nmearl/pyfocal#102]
This might just be a work-in-progress issue, but when I created a layer from a model, and then tried to delete that layer with the "trash can" icon, nothing happens. I presume it's supposed to delete the layer?

**Comment by nmearl** [comment]
Correct. #4 and #66 are still on-going. Later today, should be in.

**Comment by eteq** [comment]
Gotcha.  I think this is subtly different from #66 because this is about removing a *layer* and that's about removing a model from the GUI panel in the lower-right.  But it might all be inter-related.

**Comment by nmearl** [comment]
Implemented in #110.

**Comment by eteq** [comment]
:clap:
