### ISSUE TITLE
Model list names reset after update

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#11]
Currently, there is no persistence is using custom model names in the model list. That is, they only last until the model list is updated again.

**Comment by pllim** [comment]
@nmearl , is this not related to the bug I just mentioned in sprint tag up? Perhaps I misunderstood?

**Comment by nmearl** [comment]
This is not. This is because when the user changes the name of the model in GUI, the change is not propagated back to the model object. Thus, when the list is updated, the changes are dumped.

**Comment by pllim** [comment]
Ah, okay. I'll open a separate issue.

**Comment by nmearl** [comment]
Fixed in #72.
