### ISSUE TITLE
Implement model fitting

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#17]
Allow population of model fitting drop-down and running of code to populate the model list objects.

**Comment by ibusko** [comment]
I have some comments written here:

https://github.com/ibusko/modelgui/blob/master/compound_model_issues

summarizing some things I found when attempting to connect astropy compound models with GUI views of the models. This work is by far not done yet and the issues I found might be wrong, or, better said, easily worked around by some still unbeknown (to me) feature in astropy.

**Comment by nmearl** [comment]
I'm not sure if you've had a chance to look at how the model fitting is implemented in Pyfocal, but you should try and install it locally to have a go.

All model generation and arithmetic expressions for creating compound models that act on data objects is currently working and implemented. It allows the user to change any parameter value, and update the model (compound or otherwise) in the viewer.

In most cases, the approach is what you're hinting at in one of your last paragraphs. That is, only individual models are associated with a data object, and then those models are created into a compound model as needed. This compound model is **never** manipulated, but it is stored until the next time any of the components get updated, and the compound model is regenerated.

**Comment by nmearl** [comment]
Take a look at #26 to get started on a local installation.

**Comment by ibusko** [comment]
Indeed, I looked into the pyfocal repo and see that you solved the arbitrary expression problem. In an elegant way too! 

I have two questions unrelated to the above: 

(i) is the existing layer architecture digging deeper into parameter instances in order to give the user access to parameter attributes such as bounds and ties? 

(ii) do you think that adding (or adapting) to pyfocal the code that writes an arbitrary model to/from file would be a useful? I think a common use case, especially with large models (many components) is the need to quickly write and read the model currently being worked on to file.

**Comment by nmearl** [comment]
i. Currently, none of the bounds/tied parameter functionality is exposed to the user. Since that's more a part of the fitting (which isn't implemented) than just generation models and showing them on the plots. I haven't thought much on how we might implement a more complicated and involved fitting gui that allows the user to e.g. define callables and such. That might have to be a "plugin" thing where the user must write their own python script that can then be registered with pyfocal.

ii. I do think having a model io would be a benefit. Especially, as you've said, in the case where there are several models.

**Comment by ibusko** [comment]
Using astropy's fitting package requires scipy as a dependency.

**Comment by pllim** [comment]
@ibusko , is adding "scipy" to "install_requires" in `setup.py` sufficient?

**Comment by ibusko** [comment]
I believe so. I can do that and then see what happens ...

**Comment by nmearl** [comment]
Closing, as the gist of this issue has been implemented.
