### ISSUE TITLE
Removed unnecessary files from repo tracking

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#18]
Namely, `__pycache__` directories and `*.pyc` files. In general, anything that is generated during build or install phase do not need to be in the repo.

**Comment by nmearl** [comment]
Thanks. I transferred the git history from GitLab where this was private repo before. The .gitignore wasn't copied over. I've updated the repo with 664dd8ccb027b9dc1be2cc789d73a83899b59da0.
