### ISSUE TITLE
ImportError qtpy.QtWidgets

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#24]
Under Anaconda, I am unable to start `pyfocal`. Am I missing some dependency? `qtpy` is nothing I have heard of before.

```python
Traceback (most recent call last):
  File ".../bin/pyfocal", line 9, in <module>
    load_entry_point('pyfocal==0.1a1', 'console_scripts', 'pyfocal')()
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
  File ".../site-packages/pyfocal-0.1a1-py2.7.egg/pyfocal/app.py", line 7, in <module>
    from qtpy.QtWidgets import *
ImportError: No module named qtpy.QtWidgets
```

**Comment by nmearl** [comment]
qtpy is an abstraction layer that was created by the Spyder team. All it does is look at your system and determine whether you have PyQt5, PyQt4 or PySide, and uses the appropriate library.

What happens when you try `python -c "from qtpy.QtWidgets import *"` ?

**Comment by pllim** [comment]
I don't have Spyder. In your documentation, there is no mention of it. Having this dependency just for a convenience abstraction layer seems like an overkill to me. Also, what if I have all of the above, but I wish to use a specific one? Would be nicer to have a `--toolkit` command line argument like Ginga.

https://github.com/ejeschke/ginga/blob/master/ginga/gw/GwHelp.py

**Comment by pllim** [comment]
Should I try to take a stab a removing Spyder dependency, just so I can run this GUI? :smile:

**Comment by nmearl** [comment]
There is no Spyder dependency. `QtPy` is a small abstraction layer that is based on a module used by the Spyder team in their development of their idea. `QtPy` itself is only a 15KB wheel.

You can, currently, simple set an environment (`QT_API`) variable to choose between either `PyQt` or `PySide` (`pyqt`, `pyside` respectively).

**Comment by nmearl** [comment]
The `setup.py` file should be extended, or a `requirements` file should be added, in order to have the package included in the install.

**Comment by nmearl** [comment]
For now, you can do a simple `pip install qtpy`, and that should fix your current error.

**Comment by nmearl** [comment]
I've updated the required packages with the 24e4d907bdf908fd8a167ec65b967194eeefdc15 commit. You should go ahead and do another `python setup.py install`, to make sure all the required packages are installed.

**Comment by pllim** [comment]
Thanks, but...

We have to be careful about introducing dependencies on packages that don't already come with Anaconda distribution (http://docs.continuum.io/anaconda/pkg-docs). Because if they become incompatible, it will be expensive to maintain in the long run. Is there any reason why we absolutely needs "qtpy" and "py_expression_eval"?

**Comment by pllim** [comment]
If they are not hard to get rid of at this point, I suggest we rid of them now before `pyfocal` becomes too dependent on them. Or on the other hand, if you think replacing them is trivial no matter how complicated `pyfocal` becomes in the future, then we can hold this off.

What do you think? @stscieisenhamer? @perrygreenfield?

**Comment by nmearl** [comment]
> Is there any reason why we absolutely needs "qtpy" and "py_expression_eval"?

Currently, it's not worth the sprint time to have to develop our own abstraction layer that is qt-agnostic (we tried this last time, and there are still bugs that now rely on crappy hacks). I'd much rather include a library that's at least supported in pypi, then have to depend on a half-baked implementation that we could not getting working reliably within the sprint time frame.

> We have to be careful about introducing dependencies on packages that don't already come with Anaconda distribution

We always have the ability to freeze a version and use anaconda skeleton to maintain our own dependencies. I disagree that this is a concern.

A similar case can be made for `py_expression_eval`; it's a ~1000 line package that obviates the need of having us spend that time implementing a full-on mathematical expression evaluator, and is small enough to include *inside* the pyfocal package if we're worried about broken dependencies in the future.

Both these packages are small and highly useful. It would be a waste of time re-implementing their functionality ourselves. I think, if there is a concern about fragmentation between pypi and anaconda managers, we should either wrap these up and make our own conda packages, or just include them within pyfocal.

**Comment by pllim** [comment]
If the licenses do not conflict, :+1: to include within `pyfocal`.
