### ISSUE TITLE
Dev installation

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#26]
I'd like the developers to try and to install and run Pyfocal locally. Currently, it is built to support both PyQt4 and PyQt5, but now that Qt4 is no longer being developed or supported, I'd prefer that we use PyQt5 as the recommended build.

As it is now, I've updated the installation instructions to target PyQt5, and I'd like each of you to try and get Pyfocal up and running.

The instructions are [here](http://pyfocal.readthedocs.org/en/latest/installation.html).

Please use this issue for any problems/comments/concerns.

@pllim @ibusko

**Comment by nmearl** [comment]
Obviously, a lot of people are still using python2, so the instructions will be updated in consideration of that (since currently, it mainly targets a python3/pyqt5 system).

**Comment by pllim** [comment]
AFAIK Anaconda does not have Qt5 yet. I use Anaconda distribution.

**Comment by nmearl** [comment]
There are several channels in the Anaconda package repo for PyQt5, and the [installation documentation](http://pyfocal.readthedocs.org/en/latest/installation.html) offer one that can be used and how to install it using Anaconda.

Otherwise, the installation instructions have been updated for those who are using python2 + PyQt4. Keep in mind that I have not tested using that combination at all, and it lacks a lot of the improvements offered in PyQt5.

**Comment by nmearl** [comment]
I should mention that a usable generic spectra is available at

```
/user/nearl/generic_spectra.fits
```

**Comment by pllim** [comment]
Both @ibusko and I were able to install and get the GUI to pop up.
