### ISSUE TITLE
Do we need ui.qt.uic in the repo?

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#29]
I am not very sure what `pyfocal.ui.qt.uic` is supposed to do in the package.

**Comment by pllim** [comment]
Somewhat related: The following files in the repo claims to be generated by something else, so do they really need to be version controlled if they can be generated on-the-fly?

* `ui/qt/icon_resource_rc.py`
* `ui/qt/mainwindow.py`
* `ui/qt/plotsubwindow.py`

**Comment by nmearl** [comment]
The uic directory contains the sources for the qt files used with the Qt Creator program to generate gui objects. I want these versioned, so, yes, I very much want to keep them in the repo.

> The following files in the repo claims to be generated by something else

These are the results of the conversion from the source files to python. These are what are actually used when you launch the application. They are necessary.

**Comment by pllim** [comment]
Okay.
