### ISSUE TITLE
pyqtgraph ROI got unexpected handlePen keyword

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#32]
It appears that `pyfocal` is depending on an unmerged change in `pyqtgraph` (pyqtgraph/pyqtgraph#271), am I right?

Therefore, it is not compatible with the `pyqtgraph` that comes with Anaconda (or any other env for that matter), and requires user to actually install it from the unmerged PR.

**Comment by pllim** [comment]
Traceback:
```python
Traceback (most recent call last):
  File ".../Pyfocal-0.1a1-py2.7.egg/pyfocal/ui/controller.py", line 204, in new_model_layer
    formula=self.viewer.current_model_formula)
  File ".../Pyfocal-0.1a1-py2.7.egg/pyfocal/interfaces/managers.py", line 194, in get_compound_model
    result = np.sum(models) if len(models) > 1 else models[0]
IndexError: list index out of range
Traceback (most recent call last):
  File ".../Pyfocal-0.1a1-py2.7.egg/pyfocal/ui/widgets/plots/plot.py", line 61, in add_roi
    hoverPen='r', handlePen='k')
  File ".../pyqtgraph/graphicsItems/ROI.py", line 1480, in __init__
    ROI.__init__(self, pos, size, **args)
TypeError: __init__() got an unexpected keyword argument 'handlePen'
```

**Comment by nmearl** [comment]
This why the instructions state to use `pip install -r requirements.txt`. You shouldn't be installing the dependencies yourself, `pip` will install the correct dependency. The user should not have to worry about it.

**Comment by pllim** [comment]
You can't rely on *everyone* to follow instructions. :wink: 

It's good to have this documented anyway. If nothing else, to remind us to remove that requirement when your PR is merged by `pyqtgraph`.

**Comment by pllim** [comment]
Also, requirements like this might complicate things for users that already use distributed `pyqtgraph` for something else. I don't think that is the case for us, but you never know.

**Comment by nmearl** [comment]
The custom pyqtgraph has been removed as a dependency. Now using the official package.
