### ISSUE TITLE
Commit does not auto trigger RTD build

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#34]
It would be nice if RTD auto re-build the documentation at http://pyfocal.readthedocs.org/en/latest/ upon a commit.

**Comment by nmearl** [comment]
I went ahead and added the webhook to this repository. Commits should now trigger building the docs.

**Comment by pllim** [comment]
Thanks, let leave this open until we can see it in action after the next commit. :smile:

**Comment by pllim** [comment]
Merging #39 did not trigger auto-rebuild.

https://readthedocs.org/projects/pyfocal/builds/ (the last build was 2 days ago)

**Comment by nmearl** [comment]
I just committed, and the docs attempted to build, so the webhook is working. It seems, however, that the documents failed.

See [https://readthedocs.org/projects/pyfocal/builds/3721390/](https://readthedocs.org/projects/pyfocal/builds/3721390/).

**Comment by pllim** [comment]
It is choking on the "install requires scipy" part. Since you own the RTD account, are you able to fix that on your end?

**Comment by nmearl** [comment]
You should be able to see the build failures in the above link, but it looks like it's failing to build the scipy wheel, and that's throwing a wrench in the system.

**Comment by pllim** [comment]
The latest error is different:
```
Obtaining file:///home/docs/checkouts/readthedocs.org/user_builds/pyfocal/checkouts/latest (from -r /home/docs/checkouts/readthedocs.org/user_builds/pyfocal/checkouts/latest/requirements.txt (line 3))
    Complete output from command python setup.py egg_info:
    running egg_info
    writing requirements to Pyfocal.egg-info/requires.txt
    writing Pyfocal.egg-info/PKG-INFO
    writing top-level names to Pyfocal.egg-info/top_level.txt
    writing dependency_links to Pyfocal.egg-info/dependency_links.txt
    writing entry points to Pyfocal.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'pyfocal/ui/qt/uic/source/qdarkstyle' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/docs/checkouts/readthedocs.org/user_builds/pyfocal/checkouts/latest
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by nmearl** [comment]
Yeah, my fault. Fixed now. See [here](https://readthedocs.org/projects/pyfocal/builds/3723838/).

**Comment by pllim** [comment]
Reading rtfd/readthedocs.org#1639 , it was mentioned, "... go to the Advanced settings section in your project's admin panel and select the checkbox in Use system packages." Could you give that a try?

**Comment by nmearl** [comment]
Looks like that solved it! Docs are successfully building. Thanks, @pllim.

**Comment by pllim** [comment]
:tada:
