### ISSUE TITLE
What does "filter" mean in Data.read()?

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#35]
I am trying to create a `pyfocal.core.data.Data` object manually, so I can unit test a function. But I cannot figure out what it wants in the "filter".

```python
>>> d = Data.read(filename, filter=None)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-07a508ca516c> in <module>()
----> 1 d = Data.read(filename, filter=None)

.../Pyfocal-0.1a1-py2.7.egg/pyfocal/core/data.pyc in read(cls, *args, **kwargs)
     26         from ..interfaces.registries import io_registry
     27 
---> 28         return io_registry.read(cls, *args, **kwargs)
     29 
     30     @property

.../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/io/registry.pyc in read(cls, *args, **kwargs)
    342 
    343         reader = get_reader(format, cls)
--> 344         data = reader(*args, **kwargs)
    345 
    346         if not isinstance(data, cls):

.../Pyfocal-0.1a1-py2.7.egg/pyfocal/interfaces/loaders.pyc in fits_reader(filename, filter, **kwargs)
     27     name = os.path.basename(filename.name.rstrip(os.sep)).rsplit('.', 1)[0]
     28     hdulist = fits.open(filename, **kwargs)
---> 29     ref = loader_registry.get(filter)
     30 
     31     meta = ref.meta

.../Pyfocal-0.1a1-py2.7.egg/pyfocal/interfaces/registries.pyc in get(self, filter)
     29 
     30     def get(self, filter):
---> 31         return [x for x in self._members if x.filter == filter][0]
     32 
     33     @property

IndexError: list index out of range
```

**Comment by nmearl** [comment]
"filter" is the association of the file type to the loader functions. When you open a file, it's that string that is shown in the drop down box that allows you to select your extension filter. So, for instance, the `generic.yaml` file is loaded into the registry associated with a string composed of its name and extensions called "Generic Fits (*.fits *.mits)".

It is the identifier for that yaml file. So you query the `LoaderRegistry` with that string as an argument, and it will give you the python dictionary parsed from the yaml file, which is then used in the astropy io parsing functions.

**Comment by pllim** [comment]
This still does not work... So, how do I load your FITS spectrum into the Data object without having to go through the GUI?

```python
d = Data('generic_spectra.fits', filter='*.fits')
```

**Comment by nmearl** [comment]
Use `filter='Generic Fits (*.fits *.mits)'`

**Comment by pllim** [comment]
Ah, okay. So it's very picky to the words. Got it, thanks!
