### ISSUE TITLE
Installing pyqt5 with anaconda 2

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#36]
It appears that you're able to install pyqt5 with an anaconda 2.7 distribution, but it will not install a python 3 distribution simultaneously.

The instructions may need to be updated to indicate that you'll have to have a python 3 virtual environment, or have a system-level python3 installation outside of anaconda in order to run the pyqt5 version.

**Comment by pllim** [comment]
I think your latest doc is pretty clear on this.
