### ISSUE TITLE
Thoughts about statistics module

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#37]
Looking at `extract()`, `stats()`, and `eq_width()` functions under `pyfocal.analysis.statistics`, they can just as easily be methods attached to `pyfocal.core.data.Data` class. This is because they operate with the assumption that input data is already a `Data` instance anyway.

Something to think about.

**Comment by nmearl** [comment]
It's a possibility. It goes back to the whole "function" vs "method" debate. The rationale was that the `Data` objects should be purely data containers, like the `ndarrays` they subclass. Then, you would build modules around them.

**Comment by pllim** [comment]
Yes, it can be designed either way. Let's keep this open for now and see if others have any thoughts.

c/c @stscieisenhamer, @perrygreenfield, @ibusko, @hcferguson

**Comment by pllim** [comment]
Given all the other more pressing issues. This is fine for now.
