### ISSUE TITLE
extract() does not work

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#38]
`Data` class  has neither `set_x()` nor `set_y()` implemented.

```python
>>> data
Data([ 0.09934656, -0.02764913,  0.12954146, ...,  0.07568395,  0.34271905, -0.32397091])
>>> extract(data, (10000, 20000))
.../Pyfocal-0.1a1-py2.7.egg/pyfocal/analysis/statistics.pyc in extract(data, x_range)
     25 
     26     result = Data(x[slice])
---> 27     result.set_x(x[slice], unit=spectrum_data.x.unit)
     28     result.set_y(y[slice], unit=spectrum_data.y.unit)
     29 

AttributeError: 'Data' object has no attribute 'set_x'
```

**Comment by nmearl** [comment]
Correct. Most of the functions probably don't work. The entire module has been copied wholesale from what Jonathan did during the previous SpecView. Only the statistics stuff has been updated for this sprint.

**Comment by pllim** [comment]
`stats()` does not work with `Data` object directly either. I'll fix them.
