### ISSUE TITLE
ui.qt files generated by uic need to support all qt4/qt5/pyside

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#41]
For example, e5da327db2a2168b35a9db637dd2d13c93b40c0c reverted a change that was made to be Qt4 compatible in `ui/qt/mainwindow.py`.

Ideally, there should be different versions for each supported toolkit (Qt4, Qt5, PySide, etc) and then `pyfocal` can choose the compatible one to use depending on what the user has.

**Comment by nmearl** [comment]
Changes should not have been made directly to `ui/qt/mainwindow.py`.

Ideally, the generated python files should be done such that they conform to PyQt5 standards. `qtpy` is designed to regress using the PyQt5 format. We should be designing all gui files to conform to PyQt5, and rely on `qtpy` for dealing with PyQt4/PySide, as per `qtpy` documentation instructions.

The `sizeAdjustPolicy` was erroneously added by the Qt Creator application, and has been fixed.

**Comment by pllim** [comment]
Ok, thanks!
