### ISSUE TITLE
Model list clears unexpectedly

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#55]
I can recreate it with the following workflow:

1. Open a spectrum in Pyfocal. The generic test FITS spectrum will do.
2. Select a retangular ROI, say, around the Gaussian feature.
3. Add a Gaussian model.
4. Create a layer slice.
5. Switch to slice view.
6. Switch back to main layer. Now the model is no longer listed.

**Comment by nmearl** [comment]
Only a model layer will display a model. Highlighting either "generic_spectra Layer" or "generic_spectra Layer Slice" will show an empty model list. You can populate this model list, but your only option is to hit the "Create" button, which creates a new `ModelLayer` as a child to the `Layer` object, and is the thing that actually holds the models. From this `ModelLayer`, you can only update the model (notice that the "Create" button is gone). You can go back to the `generic_spectra Layer Slice` and create a new `ModelLayer` object by populating the model list and hitting "Create" again.

Does this make sense?

**Comment by pllim** [comment]
Ah, okay, thanks! So, it is just user error. I'll update the document to reflect this.

Also, why is the "create/update" button so far down? Shouldn't it be above the "Fitting Routine" area?

**Comment by nmearl** [comment]
Originally, I was thinking that the "Perform Fit" button would not create/update the model layer. Instead, it would just populate the values in the model list. Then the user would have to click "Create" or "Update" to actually propagate the changes to the visible plot.

But it has been implemented as such that hitting "Perform Fit" also creates/updates the plot. Perhaps we should either

1. Make it so "Perform Fit" only updates the parameters in the model list, and leave the creation/updating of the plot to the user, or
2. Move the "Fitting Routine" area below the "Create/Update" button area.

**Comment by pllim** [comment]
Regarding GUI layout, I think it is best to ask the scientists, who are our target users.

**Comment by nmearl** [comment]
I was thinking about this more. Right now, models are attached to a `Layer` object until a child `ModelLayer` is created (hence why when you change layers, the models will disappear). The alternative is to have the models be attached to the gui, and be persistent. However, the model is created based on the currently selected `Layer`. Is it too much to expect the user to be aware of the fact that they could accidentally change their active layer? Or should we assume that they will pay attention?

**Comment by pllim** [comment]
This whole "layer" business is a bit confusing for a regular user. We need to think of a more user friendly way to present the layers, but that can be done in the future when API is more stable.

**Comment by nmearl** [comment]
Closing for now. Open another issue for high-level discussion on layers.
