### ISSUE TITLE
What is "arithmetic behavior"?

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#56]
I have no idea what to enter in that text box under "Arithmetic Behavior".

**Comment by nmearl** [comment]
"Arithmetic Behavior" describes how the models are going to be combined. For instance, if I added a "Linear" model and a "Gaussian" model, I could put "Linear + Gaussian" or "Linear * Gaussian" in the "Arithmetic Behavior" box, and when I hit "Create" or "Update", that arithmetic operation will be performed to produce the compound model.

A user can also change the name of model. For instance, if you have two gaussians, you'd want to rename them "Gaussian1" and "Gaussian2", then in the "Arithmetic Behavior" box enter "Gaussian1 - Gaussian2", for example. However, as described in #11, these name changes will reset when the mode list is updated.

**Comment by pllim** [comment]
Thanks for the clarification!

Due to #11, should we hold off on advertising this in the doc until after the bug fix then? Or you want me to write something about it anyway?

**Comment by nmearl** [comment]
We can hold off for now. I think I know how to fix it easily (by grabbing the names for the astropy objects instead of the dictionary).

**Comment by nmearl** [comment]
The naming issue described in #11 has been fixed in #72.

**Comment by pllim** [comment]
Resolved in #77
