### ISSUE TITLE
pyfocal won't read some test files

### ISSUE THREAD

**Issue by ibusko** [nmearl/pyfocal#61]
Was anybody able to read the test fies in /astro/3/jwst_da_sprint_testdata/SpecView/gderosa/ ? 

I get an error from line 200 in astropy/utils/data.py , in which the constructor for an io.FileIO object is called. With these files, the constructor crashes and the resulting file object is None, so the main code crashes as well.

**Comment by pllim** [comment]
Which file exactly? She has two different directories.

**Comment by pllim** [comment]
I just tried one of the COS files using the latest master version, and I get a different traceback.

```python
Traceback (most recent call last):
  File ".../pyqtgraph/graphicsItems/ErrorBarItem.py", line 146, in boundingRect
    self.drawPath()
  File ".../pyqtgraph/graphicsItems/ErrorBarItem.py", line 84, in drawPath
    p.moveTo(x[i], y1[i])
TypeError: arguments did not match any overloaded call:
  QPainterPath.moveTo(QPointF): argument 1 has unexpected type 'numpy.float64'
  QPainterPath.moveTo(float, float): argument 2 has unexpected type 'numpy.ndarray'
```

**Comment by pllim** [comment]
For the other directory, it is because the data format is not the one expected by "generic FITS" YAML. 
```python
>>> from astropy.io import fits
>>> pf = fits.open(filename)
>>> pf.info()
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     107   (1161, 1, 4)   float32
```

**Comment by pllim** [comment]
For the files under "kassin", I don't think the "generic FITS" YAML works either because Pyfocal failed to recreate the dispersion from WCS. In this case, it is unnecessary, because dispersion is already given in the table. In addtion, the YAML HDU definition also does not match the actual table columns.

```python
>>> pf.info()
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU       4   ()              
1    Bxspf-B     BinTableHDU    131   1R x 15C     [4096E, 4096E, 4096E, 4096I, 4096I, 4096I, 4096I, 4096I, E, E, E, J, J, 4096E, E]   
2    Bxspf-R     BinTableHDU    131   1R x 15C     [4096E, 4096E, 4096E, 4096I, 4096I, 4096I, 4096I, 4096I, E, E, E, J, J, 4096E, E]   
3    Horne-B     BinTableHDU    140   1R x 15C     [4096E, 4096E, 4096E, 4096I, 4096I, 4096I, 4096I, 4096I, E, E, E, J, J, 4096E, E]   
4    Horne-R     BinTableHDU    140   1R x 15C     [4096E, 4096E, 4096E, 4096I, 4096I, 4096I, 4096I, 4096I, E, E, E, J, J, 4096E, E]   
>>> pf[1].data.columns
ColDefs(
    name = 'SPEC'; format = '4096E'
    name = 'LAMBDA'; format = '4096E'
    name = 'IVAR'; format = '4096E'
    name = 'CRMASK'; format = '4096I'
    name = 'BITMASK'; format = '4096I'
    name = 'ORMASK'; format = '4096I'
    name = 'NBADPIX'; format = '4096I'
    name = 'INFOMASK'; format = '4096I'
    name = 'OBJPOS'; format = 'E'
    name = 'FWHM'; format = 'E'
    name = 'NSIGMA'; format = 'E'
    name = 'R1'; format = 'J'
    name = 'R2'; format = 'J'
    name = 'SKYSPEC'; format = '4096E'
    name = 'IVARFUDGE'; format = 'E'
)
```

**Comment by ibusko** [comment]
to @pllim : "Which file exactly? She has two different directories."

Any file in any of those directories.

**Comment by pllim** [comment]
@ibusko , I tested all the files in the test data directory and left my comments above. FYI.

I think the solution is to add more YAML files that can properly load each of those formats.

**Comment by pllim** [comment]
@ibusko , with #81, you should now be able to load HST/COS data from Gisella and all the data from Susan. Use the latest master version. Or if you are using your own branch for your PR, rebase to latest master.

However, I just cannot get Gisella's other data (`MDM1.3_CCDSPEC`) to load. Its format is too weird. I can't even get `astropy.table.Table` to load it.

**Comment by pllim** [comment]
@ibusko , to clarify, you have to open those data files from GUI, not from command line. Then select either the "HST/COS" or "Keck/DEIMOS" file type from the file dialog.

**Comment by pllim** [comment]
I'll see if I can hack around to load Gisella MDM files tomorrow... FYI.

**Comment by pllim** [comment]
@ibusko , if you use the new "KittPeak/MDM" file type, you should be able to open Gisella's `nXXXX_*.fits` files. All test data can now be opened.
