### ISSUE TITLE
How does one measure equivalent width?

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#62]
I'm not instantly finding how to measure equivalent with from the GUI, and there's no documentation yet. Perhaps it isn't hooked back into the GUI?

**Comment by pllim** [comment]
I don't think it is implemented yet. See #14.

**Comment by pllim** [comment]
There is a function for it in the `analysis.statistics` module but I don't think GUI has a way to call it yet. @nmearl can correct me if I am wrong.

Also, do you plan to measure it from the fitted model, or from raw data? If from fitted model, it shouldn't be calculated from the `statistics` module, but should instead be calculated directly, say, from the fitted Gaussian.

**Comment by pllim** [comment]
Also see http://pyfocal.readthedocs.org/en/latest/api/statistics.html#pyfocal.analysis.statistics.eq_width

**Comment by nmearl** [comment]
Implemented in the GUI in #110.
