### ISSUE TITLE
ROI issues

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#63]
Various issues/suggestions:

- [x] Don't see a need to have circles and hexagons as options
- [x] The typical selection size of the rectangle would encompass the whole spectrum vertically. It would be nice to have this as the default when you select a rectangle.
- [x] I'm finding the three handles on the ROI boxes rather clunky to use. Would prefer to have handles on the corners if that's an option.

**Comment by nmearl** [comment]
Check out the latest master and let me know how you feel about the changes.
