### ISSUE TITLE
Model fitting expression evaluator may mix and match models in the wrong way

### ISSUE THREAD

**Issue by ibusko** [nmearl/pyfocal#67]
We may have a model that looks like this on the window:

> Const
> PowerLaw

with an expression like this in the expression text field:

PowerLaw / Const

This should result in always the same calculation being performed, but that is not the case. Randomly, sometimes it may result in the underlying code replacing the 'PowerLaw' entry in the expression with the Const instance, and the other way around for the other pair expression entry - instance. 

The cause of this is that the association of model names and instances involves a dictionary, which is not guaranteed to be ordered in any specific order. 

The code is around line 201 in managers.py.

**Comment by nmearl** [comment]
Fixed in #72.
