### ISSUE TITLE
Models should automatically have unique names

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#74]
As mentioned in #56, models need to be renamed if, say, there are two Gaussians defined for the same layer and user wishes to define a custom "Arithmetic Behavior". It makes more sense for Pyfocal to just automatically generate a unique model name when the model is added to a layer. For example, `Gaussian0001`, `Gaussian0002`, and so on.

**Comment by nmearl** [comment]
Done in a214744b4e4c243384e4255286acc91b2ebb4a41.

**Comment by pllim** [comment]
:+1:
