### ISSUE TITLE
Layer visibility toggle has unexpected behavior

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#75]
This is a follow up of #8.

I have two layers, and one of them unchecked. Then with the check boxes untouched, I click on the different layers to select them (highlight on the GUI). This causes the GUI to ignore my checkbox selection.

I see this on RHEL6, Python 2.7, and Qt4. I did not test under Mac/Python3/Qt5 combo.

**Comment by nmearl** [comment]
I cannot reproduce this behavior in either Python2/PyQt4 or Python3/PyQt5. Are you saying that the previously unchecked (hidden) layer comes back if you select a different layer and come back to the initial layer?

**Comment by pllim** [comment]
Not sure how to explain further in words. Perhaps I'll see how it works on your side when we meet for tag up.

**Comment by pllim** [comment]
Actually, it seems fine on real data, just not the fake data we started out with. I'm just going to close this.
