### ISSUE TITLE
bottom-right ROI handle not working

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#82]
The bottom-right handle behaves strangely for me....moves the top of the box rather than the bottom.

**Comment by nmearl** [comment]
I've removed ROIs in favor of linear regions in 85c07424f4ce17b8011dc272ad0c5cc647974bb4. Let me know what you think.

**Comment by pllim** [comment]
c/c @eteq

**Comment by hcferguson** [comment]
Works for me. I like it!
