### ISSUE TITLE
Trying to plot before having a spectrum crashes pyfocal

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#84]
Trying to create a plot window (using plot button) before having loaded a spectrum causes pyfocal to crash with a "data not defined" error message. Ultimately, we will want to trap silly user errors and issue an error message rather than exit with a traceback. 

Pyfocal also crashes with the same error message if I load the spectrum, but forget to highlight it before pushing the plot button.

**Comment by nmearl** [comment]
Fixed in a4e649c9dc06cb041d74780659f662bac04ccbcc.
