### ISSUE TITLE
Format for values of model parameters

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#98]
Model parameters are being shown to too many digits, making the exponent disappear off the right. Reporting to 3 significant figures should be sufficient (like for the statistics box).

**Comment by pllim** [comment]
This can be misleading though, because what you see might not be the exactly the values that go into the model.

**Comment by nmearl** [comment]
Done in 24b5a8c18cab5c66cc2a50dc094a839fd637a365.
